spring.application.name=tastManagement


spring.mongodb.uri=${SPRING_MONGODB_URI}
jwt.secret=${JWT_SECRET}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.springframework.core.env=DEBUG
